### DISCUSSION TITLE
Support for Route Data in Markdown frontmatter

### DISCUSSION THREAD

**Discussion by hwmaier** [hannoeru/vite-plugin-pages#279] [Ideas]
Special support for Route Data is already implemented for SFCs and JSX using a `<route />` block. Would be nice to complete the support if one could also add a route block to markdown files:

```
---
route:
   name: name-override
   meta:
     requiresAuth: true
---

# A Markdown page defining Route Data in its frontmatter
```
